jobs:
  test-build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run babel
        run: yarn prepublish
      - name: Lint code
        run: yarn lint:js
      - name: Lint styles
        run: yarn lint:styles
      - name: i18n check (en-US, fr only)
        run: yarn check:i18n-en-fr
      - name: Type check
        run: yarn tsc
      - name: Run tests
        run: yarn unit
      - name: Run a11y tests
        run: yarn a11y-test
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Semantic Release
        run: yarn semantic-release
name: Node.js CI
"on":
  pull_request: null
  push:
    branches:
      - master
      - alpha
      - beta
      - next
      - next-major
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"
      - "[0-9]+.x"
